export enum POSTBOOKING_NAVIGATION {
  VACATION_PACKAGES = "vp",
  RESERVATIONS = "reservations",
  TRAVELPLAN = "travelplan",
  MOBILEMAP = "map",
}

export enum POSTBOOKING_QUERY_PARAMS {
  tripId = "tripId",
  nav = "nav",
  day = "day",
}

export enum PB_CARD_TYPE {
  ATTRACTION = "ATTRACTION",
  TRAVELPLAN = "TRAVELPLAN",
  BAR = "BAR",
  CAR_RENTAL = "CAR_RENTAL",
  CITY = "CITY",
  FLIGHT_ARRIVING = "FLIGHT_ARRIVING",
  FLIGHT_RETURN = "FLIGHT_RETURN",
  RESTAURANT = "RESTAURANT",
  STAY = "STAY",
  STAY_PRODUCT = "STAY_PRODUCT", // this is a non vp hotel booking
  UNDEFINED = "UNDEFINED",
  TOUR = "TOUR",
  VACATION_PACKAGE = "VACATION_PACKAGE",
}

export enum PB_ITINERARY_ICON_TYPE {
  COUNTRY_FLAG = "COUNTRY_FLAG",
  FLIGHT_DEPART = "FLIGHT_DEPART",
  FLIGHT = "FLIGHT",
  CAR = "CAR",
  CAMERA = "CAMERA",
  CAR_CHECKMARK = "CAR_CHECKMARK",
  HUMAN_WALK = "HUMAN_WALK",
  CAR_DRIVING = "CAR_DRIVING",
  HOUSE_WITH_HEART = "HOUSE_WITH_HEART",
  MARKER = "MARKER",
  RESTAURANT = "RESTAURANT",
  DRINK = "DRINK",
  CALENDAR = "CALENDAR",
  UNDEFINED = "UNDEFINED",
  TOURIST_WALK = "TOURIST_WALK",
  TOURS_AND_TICKETS = "TOURS_AND_TICKETS",
}

export enum PB_ITINERARY_TRAVELMODE_TYPE {
  UNKNOWN = "UNKNOWN",
  WALK = "WALK",
  DRIVING = "DRIVING",
  FLIGHT = "FLIGHT",
}

export enum ITINERARY_SEGMENT_TYPE {
  UNASSIGNED = "UNASSIGNED",
  DAY_INTRO = "DAY_INTRO",
  FLIGHT_TO = "FLIGHT_TO",
  FLIGHT_FROM = "FLIGHT_FROM",
  CAR_PICKUP = "CAR_PICKUP",
  CAR_DROPOFF = "CAR_DROPOFF",
  CITY_AND_STAY = "CITY_AND_STAY",
  HOTEL_CHECKOUT = "HOTEL_CHECKOUT",
  ATTRACTION_VISIT = "ATTRACTION_VISIT",
  RESTAURANT = "RESTAURANT",
  BAR = "BAR",
  TOMORROW_INTRO = "TOMORROW_INTRO",
  BREAKFAST_RESTAURANTS = "BREAKFAST_RESTAURANTS",
  TRIP_INTRO = "TRIP_INTRO",
}

export enum ITINERARY_MAP_ITEM_TYPE {
  TOUR = "TOUR",
  DAY_TOUR = "DAY_TOUR",
  PACKAGE_TOUR = "PACKAGE_TOUR",
  SELF_DRIVE_TOUR = "SELF_DRIVE_TOUR",
  HOTEL = "HOTEL",
  CAR = "CAR",
  ATTRACTION = "ATTRACTION",
  DESTINATION = "DESTINATION",
  RESTAURANT = "RESTAURANT",
  BAR = "BAR",
}

export enum ITINERARY_TOUR_DIFFICULTY {
  UNDEFINED = "UNDEFINED",
  EASY = "EASY",
  MEDIUM = "MEDIUM",
  HARD = "HARD",
}

export enum PB_ACTIVE_MODAL {
  NONE,
  INFO,
  BOOKING,
}

export enum PB_TICKET_TYPE {
  FLIGHT_BOARDING_PASS = "FLIGHT_BOARDING_PASS",
  FLIGHT_ETICKET = "FLIGHT_ETICKET",
  VOUCHER = "VOUCHER",
}
