export enum GTETourAgeBand {
  TRAVELER = "TRAVELER",
  SENIOR = "SENIOR",
  ADULT = "ADULT",
  YOUTH = "YOUTH",
  CHILD = "CHILD",
  INFANT = "INFANT",
}

export enum GTETourQuestionType {
  STRING = "STRING",
  DATE = "DATE",
  DROPDOWN = "DROPDOWN",
  TEXTAREA = "TEXTAREA",
  TIME = "TIME",
  LOCATION_REF_OR_FREE_TEXT = "LOCATION_REF_OR_FREE_TEXT",
  NUMBER_AND_UNIT = "NUMBER_AND_UNIT",
}

export enum GTETourDropdownType {
  DATES = "dates",
  TRAVELERS = "travelers",
  OPTIONS = "options",
  TIMES = "times",
  LANGUAGES = "guidedLanguages",
  DEPARTURE_DROPDOWN = "DEPARTURE_DROPDOWN",
  ARRIVAL_DROPDOWN = "ARRIVAL_DROPDOWN",
}

export enum GTETourQuestionGroup {
  PER_BOOKING = "PER_BOOKING",
  PER_TRAVELER = "PER_TRAVELER",
}

export enum GTETourQuestionId {
  SPECIAL_REQUIREMENTS = "SPECIAL_REQUIREMENTS",
  AGEBAND = "AGEBAND",
  TRANSFER_DEPARTURE_MODE = "TRANSFER_DEPARTURE_MODE",
  TRANSFER_ARRIVAL_MODE = "TRANSFER_ARRIVAL_MODE",
  PASSPORT_NATIONALITY = "PASSPORT_NATIONALITY",
  PASSPORT_EXPIRY = "PASSPORT_EXPIRY",
  PICKUP_POINT = "PICKUP_POINT",
  WEIGHT = "WEIGHT",
  HEIGHT = "HEIGHT",
  TRANSFER_DEPARTURE_DATE = "TRANSFER_DEPARTURE_DATE",
  DATE_OF_BIRTH = "DATE_OF_BIRTH",
  FULL_NAMES_FIRST = "FULL_NAMES_FIRST",
  FULL_NAMES_LAST = "FULL_NAMES_LAST",
}

export enum GTETourQuestionRequired {
  MANDATORY = "MANDATORY",
  CONDITIONAL = "CONDITIONAL",
  OPTIONAL = "OPTIONAL",
}

export enum GTETourGuidedLanguageType {
  GUIDE = "GUIDE",
  AUDIO = "AUDIO",
  WRITTEN = "WRITTEN",
}

export enum GTETourProvider {
  VIATOR = "VIATOR",
}
