export enum StayProvider {
  ANIXE = "ANIXE",
  GODO = "GODO",
  MONOLITH = "MONOLITH",
  UNKNOWN = "UNKNOWN",
}

export enum PaymentType {
  PAY_BEFORE = "PAY_BEFORE",
  UNKNOWN = "UNKNOWN",
}

export enum OrderStayCancellationType {
  UNKNOWN = "UNKNOWN",
  FREE = "FREE",
  FEE_APPLIES = "FEE_APPLIES",
  NON_REFUNDABLE = "NON_REFUNDABLE",
}

export enum MealType {
  ROOM_ONLY = "ROOM_ONLY",
  SELF_CATERING = "SELF_CATERING",
  BED_AND_BREAKFAST = "BED_AND_BREAKFAST",
  DINNER_ONLY = "DINNER_ONLY",
  LUNCH_ONLY = "LUNCH_ONLY",
  HALF_BOARD = "HALF_BOARD",
  HALF_BOARD_PLUS = "HALF_BOARD_PLUS",
  FULL_BOARD = "FULL_BOARD",
  FULL_BOARD_PLUS = "FULL_BOARD_PLUS",
  ALL_INCLUSIVE = "ALL_INCLUSIVE",
  ALL_INCLUSIVE_LIGHT = "ALL_INCLUSIVE_LIGHT",
  ALL_INCLUSIVE_ULTRA = "ALL_INCLUSIVE_ULTRA",
  ALL_INCLUSIVE_PLUS = "ALL_INCLUSIVE_PLUS",
}

export enum RoomType {
  SINGLE_ROOM = "SINGLE_ROOM",
  DOUBLE_ROOM = "DOUBLE_ROOM",
  TWIN_BED_ROOM = "TWIN_BED_ROOM",
  TRIPLE_ROOM = "TRIPLE_ROOM",
  QUADRUPLE_ROOM = "QUADRUPLE_ROOM",
}

export enum BedType {
  SINGLE = "SINGLE",
  DOUBLE = "DOUBLE",
  QUEEN = "QUEEN",
  KING = "KING",
  UNKNOWN = "UNKNOWN",
}

export enum BookingWidgetView {
  Default,
  Dates,
  Details,
  RoomTypes,
}

export enum RoomAmenity {
  AIR_CONDITIONING = "AIR_CONDITIONING",
  MINI_BAR = "MINI_BAR",
  SAFE_DEPOSIT_BOX = "SAFE_DEPOSIT_BOX",
  TOWELS = "TOWELS",
  TV = "TV",
  PRIVATE_KITCHEN = "PRIVATE_KITCHEN",
  HAIR_DRYER = "HAIR_DRYER",
  REFRIGERATOR = "REFRIGERATOR",
  KITCHEN = "KITCHEN",
  FREE_TOILETRIES = "FREE_TOILETRIES",
  PETS_ALLOWED = "PETS_ALLOWED",
  SOUNDPROOFING = "SOUNDPROOFING",
  FAN = "FAN",
  HEATING = "HEATING",
  BALCONY = "BALCONY",
  SUN_TERRACE = "SUN_TERRACE",
  TERRACE = "TERRACE",
  SEA_VIEW = "SEA_VIEW",
  GARDEN_VIEW = "GARDEN_VIEW",
  MOUNTAIN_VIEW = "MOUNTAIN_VIEW",
  CITY_VIEW = "CITY_VIEW",
  POOL_VIEW = "POOL_VIEW",
  NON_SMOKING_ROOMS = "NON_SMOKING_ROOMS",
  DESK = "DESK",
  ADDITIONAL_BATHROOM = "ADDITIONAL_BATHROOM",
  ADDITIONAL_TOILET = "ADDITIONAL_TOILET",
  BATH_ROBE = "BATH_ROBE",
  SHAMPOO = "SHAMPOO",
  CONDITIONER = "CONDITIONER",
  SLIPPERS = "SLIPPERS",
  PAJAMAS = "PAJAMAS",
  SHOWER_CHAIR = "SHOWER_CHAIR",
  SEATING_AREA = "SEATING_AREA",
  SOFA = "SOFA",
  SOFA_BED = "SOFA_BED",
  SATELLITE_CHANNELS = "SATELLITE_CHANNELS",
  BLACKOUT_CURTAINS = "BLACKOUT_CURTAINS",
  TELEPHONE = "TELEPHONE",
  COFFEE_MACHINE = "COFFEE_MACHINE",
  COFFEE_OR_TEA_MAKER = "COFFEE_OR_TEA_MAKER",
  KITCHENWARE = "KITCHENWARE",
  KITCHENETTE = "KITCHENETTE",
  OVEN = "OVEN",
  STOVE = "STOVE",
  TOASTER = "TOASTER",
  DISHWASHER = "DISHWASHER",
  WASHING_MACHINE = "WASHING_MACHINE",
  LAPTOP_SAFE_BOX = "LAPTOP_SAFE_BOX",
}
