export enum StaySearchGTEValueProp {
  SUPPORT24_HOURS = "SUPPORT24_HOURS",
  INSTANT_CONFIRMATION = "INSTANT_CONFIRMATION",
  CANCELLATION_FREE = "CANCELLATION_FREE",
  CANCELLATION_CONDITIONAL = "CANCELLATION_CONDITIONAL",
}
export enum StaySearchGTEQuickFactType {
  WIRELESS_INTERNET = "WIRELESS_INTERNET",
  DISTANCE_FROM_CITY_CENTER = "DISTANCE_FROM_CITY_CENTER",
  PRODUCT_CATEGORY = "PRODUCT_CATEGORY",
  TIME_OF_CHECK_IN = "TIME_OF_CHECK_IN",
  TIME_OF_CHECK_OUT = "TIME_OF_CHECK_OUT",
  TIME_OF_CHECK_IN_AND_OUT = "TIME_OF_CHECK_IN_AND_OUT",
  PARKING = "PARKING",
  STAR_RATING = "STAR_RATING",
  BREAKFAST = "BREAKFAST",
}
export enum StaySearchBreakfastAvailabilities {
  BREAKFAST_AVAILABLE_FOR_FREE = "BREAKFAST_AVAILABLE_FOR_FREE",
  BREAKFAST_AVAILABLE = "BREAKFAST_AVAILABLE",
  BREAKFAST_IN_THE_ROOM = "BREAKFAST_IN_THE_ROOM",
}
export enum StaySearchWifiAvailabilities {
  WIFI_AVAILABLE = "WIFI_AVAILABLE",
  WIFI_AVAILABLE_FOR_FREE = "WIFI_AVAILABLE_FOR_FREE",
  WIRELESS_INTERNET = "WIRELESS_INTERNET",
  PAID_WIFI = "PAID_WIFI",
  PORTABLE_WIFI = "PORTABLE_WIFI",
}

export enum StaySearchParkingAvailabilities {
  ACCESSIBLE_PARKING = "ACCESSIBLE_PARKING",
  PARKING_GARAGE = "PARKING_GARAGE",
  SECURED_PARKING = "SECURED_PARKING",
  STREET_PARKING = "STREET_PARKING",
  PRIVATE_PARKING = "PRIVATE_PARKING",
  FREE_PARKING = "FREE_PARKING",
  PARKING_AVAILABLE = "PARKING_AVAILABLE",
}

export enum StayFilterSectionType {
  ReviewScore = "Review_Score",
  MealsIncluded = "Meals_Included",
  RoomPreferences = "Room_preferences",
  Categories = "Categories",
  HotelAmenities = "Hotel_amenities",
  StarRatings = "Star_ratings",
  Price = "Price",
}
