import { RequestMock } from "testcafe";

const constructMockCartResponse = ({
  cartData,
  preferredPaymentProvider,
}: {
  cartData: any;
  preferredPaymentProvider: string;
}) => ({
  data: {
    carProductBaseUrl: "car-rental",
    carSearchBaseUrl: "iceland-car-rentals",
    cartWithPaymentProviders: {
      cart: {
        ...cartData,
        itemCount: 1,
        totalPrice: 1230.108,
        totalOnArrival: 0,
        customerInfo: {
          name: null,
          email: null,
          nationality: null,
          phoneNumber: null,
          __typename: "OrderCartCustomerInfo",
        },
        __typename: "OrderCartInfo",
      },
      paymentProviderSettings: {
        serverTime: "2022-04-12T22:18:24.645Z",
        preferredPaymentProvider,
        paymentProviders: [
          {
            suggestedCurrency: "USD",
            provider: "ADYEN",
            clientKey: "test_RPFJ3LDO3VDV3P7DKXL3VZNXFEUW3C5W",
            merchantAccount: "GuideToIcelandECOM-uninsured",
            environment: "test",
            enableSaveCard: false,
            clientPublicKey:
              "10001|AE6BCFDD6DF47C3CE5DB7211C3DECDD5B36CFE773740E89DC6A6407A2A64FC7BF082A238E82F7C14DEBECF7F05FFF72202978706F42D4DE7F9F0C9D8B01DD776916AB09A1301F6EFECEEE5BDA5CD03FF00421E176A4E225CECDFDC9AA212A9F8AC79A7D693AAD01FE85144F4264DDF6271F7DD45B1394017B195477AF75C7A2BB35B2B09110D190BE59636B1B24AD9FD082C899DDF30256362A4F950A04BD9C787770EC83614A4600AABE041FA4499C628BB7DE1E435C14C82935EC18A18AE1E47FB7F70D756F6E6FC751D42BEB193A83FDE4F2C0ECBD732E438ED3A4DD303D1ACE564EAD449D84700539747DCD8C2285CFED126F48BCAA48E361E69EA60089D",
            clientLibraryLocation: "https://test.adyen.com/hpp/cse/js/8015821177360381.shtml",
            additionalProviderSettings: [],
            __typename: "OrderCartPaymentProviderSettings",
          },
          {
            suggestedCurrency: "ISK",
            provider: "SALTPAY",
            clientKey: "891451_puZw2H22X7Wcf5ErHxDmOmr1XlnlG6OhZn",
            merchantAccount: "guidetoiceland-is",
            environment: "test",
            enableSaveCard: false,
            clientPublicKey: null,
            clientLibraryLocation: null,
            additionalProviderSettings: [
              {
                suggestedCurrency: "EUR",
                provider: "SALTPAY",
                clientKey: "891451_puZw2H22X7Wcf5ErHxDmOmr1XlnlG6OhZn",
                merchantAccount: "guidetoiceland-is",
                environment: "test",
                enableSaveCard: false,
                clientPublicKey: null,
                clientLibraryLocation: null,
                __typename: "OrderCartPaymentProviderSettings",
              },
            ],
            __typename: "OrderCartPaymentProviderSettings",
          },
        ],
        __typename: "OrderCartPaymentProviders",
      },
      __typename: "OrderGetCartWithProvidersResult",
    },
  },
});

export const cartTourMock = {
  id: 5598,
  tourId: 5598,
  linkUrl: "/book-holiday-trips/5bb49ab1ba98c",
  departureInformation: "Please bring your voucher to the ticket desk for entry.",
  category: {
    id: 268,
    name: "Culture Tours",
    uri: "/book-trips-holiday/adventure-tours/culture-tours",
    __typename: "OrderTourCartCategory",
  },
  type: "Day tours",
  adults: 1,
  teenagers: 0,
  children: 0,
  discountAmount: 0,
  discountPercentage: 0,
  extras: [],
  valueProps: [
    {
      iconId: null,
      title: "Free cancellation",
      __typename: "OrderValueProp",
    },
    {
      iconId: null,
      title: "24/7 customer support",
      __typename: "OrderValueProp",
    },
    {
      iconId: null,
      title: "Best price guarantee",
      __typename: "OrderValueProp",
    },
    {
      iconId: null,
      title: "Instant confirmation",
      __typename: "OrderValueProp",
    },
  ],
  specs: [
    {
      iconId: "tourStarts",
      name: "Tour starts",
      value: "Keflavík",
      __typename: "OrderProductSpec",
    },
    {
      iconId: "duration",
      name: "Duration",
      value: "2 hours",
      __typename: "OrderProductSpec",
    },
    {
      iconId: "difficultyEasy",
      name: "Difficulty",
      value: "Easy",
      __typename: "OrderProductSpec",
    },
    {
      iconId: "guidedLanguage",
      name: "Languages",
      value: "English, German, Icelandic, French, Norwegian",
      __typename: "OrderProductSpec",
    },
    {
      iconId: "availability",
      name: "Available",
      value: "All year",
      __typename: "OrderProductSpec",
    },
    {
      iconId: "minAge",
      name: "Minimum age",
      value: "None",
      __typename: "OrderProductSpec",
    },
  ],
  durationSec: 7200,
  durationText: "2 hours",
  title: "Entry to the Icelandic Museum of Rock 'n' Roll with an iPad Guided Tour",
  cartItemId: "tours-1",
  totalPrice: 1500,
  imageUrl:
    "https://guidetoiceland.imgix.net/433340/x/0/img-0011.jpg?crop=faces&fit=crop&h=239&ixlib=php-3.3.0&w=239",
  available: true,
  editable: true,
  from: "2022-05-16T00:00:00.000Z",
  to: "2022-05-16T00:00:00.000Z",
  updated: "2022-04-11T13:26:47.000Z",
  createdTime: "2022-04-11T13:26:47.000Z",
  advancedNoticeSec: 0,
  whatToBringItems: [],
  pickup: "NO_PICKUP",
  pickupLocation: null,
  startingLocation: {
    locationName: "Keflavík",
    __typename: "OrderTourCartLocation",
  },
  endingLocation: {
    locationName: "Keflavík",
    __typename: "OrderTourCartLocation",
  },
  __typename: "OrderTourCartInfo",
};

export const cartSelfDriveTourMock = {
  id: 770,
  tourId: 770,
  linkUrl: "/book-holiday-trips/8-day-self-drive-tour-circle-of-iceland",
  departureInformation: "Please bring your voucher to the ticket desk for entry.",
  category: {
    id: 277,
    name: "Summer Self Drive Tours",
    uri: "/book-trips-holiday/self-drive-tour-packages/summer-self-drive-tours",
    __typename: "OrderTourCartCategory",
  },
  type: "Self-drive tours",
  adults: 1,
  teenagers: 0,
  children: 0,
  discountAmount: 0,
  discountPercentage: 0,
  extras: [
    {
      extraId: "76776",
      name: "Accommodation",
      answer: "Comfort (private bath)",
      included: false,
      price: 0,
      required: true,
      __typename: "OrderTourCartExtra",
    },
    {
      extraId: "77273",
      name: "Activity on day 2",
      answer: "Sightseeing",
      included: false,
      price: 0,
      required: true,
      __typename: "OrderTourCartExtra",
    },
    {
      extraId: "77274",
      name: "Activity on day 3",
      answer: "Sightseeing",
      included: false,
      price: 0,
      required: true,
      __typename: "OrderTourCartExtra",
    },
    {
      extraId: "85609",
      name: "Activity on day 4",
      answer: "Sightseeing",
      included: false,
      price: 0,
      required: true,
      __typename: "OrderTourCartExtra",
    },
    {
      extraId: "77275",
      name: "Activity on day 5",
      answer: "Sightseeing",
      included: false,
      price: 0,
      required: true,
      __typename: "OrderTourCartExtra",
    },
    {
      extraId: "77276",
      name: "Activity on day 6",
      answer: "Sightseeing",
      included: false,
      price: 0,
      required: true,
      __typename: "OrderTourCartExtra",
    },
    {
      extraId: "77277",
      name: "Activity on day 7",
      answer: "Sightseeing",
      included: false,
      price: 0,
      required: true,
      __typename: "OrderTourCartExtra",
    },
    {
      extraId: "85112",
      name: "Add Dinners",
      answer: "No",
      included: false,
      price: 0,
      required: true,
      __typename: "OrderTourCartExtra",
    },
    {
      extraId: "76775",
      name: "Blue Lagoon (minimum age 2)",
      answer: "Comfort Entrance",
      included: false,
      price: 8990,
      required: true,
      __typename: "OrderTourCartExtra",
    },
    {
      extraId: "76773",
      name: "Car",
      answer: "Budget 2WD Manual",
      included: false,
      price: 17486,
      required: true,
      __typename: "OrderTourCartExtra",
    },
  ],
  valueProps: [
    {
      iconId: null,
      title: "24/7 customer support",
      __typename: "OrderValueProp",
    },
    {
      iconId: null,
      title: "Perfect travel plan",
      __typename: "OrderValueProp",
    },
    {
      iconId: null,
      title: "Fully customizable",
      __typename: "OrderValueProp",
    },
    {
      iconId: null,
      title: "Car & accommodation",
      __typename: "OrderValueProp",
    },
  ],
  specs: [
    {
      iconId: "tourStarts",
      name: "Tour starts",
      value: "Keflavík Airport",
      __typename: "OrderProductSpec",
    },
    {
      iconId: "tourStartingTime",
      name: "Starting time",
      value: "Flexible",
      __typename: "OrderProductSpec",
    },
    {
      iconId: "duration",
      name: "Duration",
      value: "8 days",
      __typename: "OrderProductSpec",
    },
    {
      iconId: "endingPlace",
      name: "Ending place",
      value: "Keflavík Airport",
      __typename: "OrderProductSpec",
    },
    {
      iconId: "difficultyEasy",
      name: "Difficulty",
      value: "Easy",
      __typename: "OrderProductSpec",
    },
    {
      iconId: "availability",
      name: "Available",
      value: "May. - Aug.",
      __typename: "OrderProductSpec",
    },
    {
      iconId: "endingTime",
      name: "Ending time",
      value: "Flexible",
      __typename: "OrderProductSpec",
    },
    {
      iconId: "minAge",
      name: "Minimum age",
      value: "None",
      __typename: "OrderProductSpec",
    },
  ],
  durationSec: 604800,
  durationText: "8 days",
  title: "Best 1 Week Summer Self Drive Tour of the Ring Road of Iceland & Golden Circle",
  cartItemId: "tours-3",
  totalPrice: 278061,
  imageUrl:
    "https://guidetoiceland.imgix.net/496560/x/0/dc-plane-solheimasandur-south-summer-wm.jpg?crop=faces&fit=crop&h=239&ixlib=php-3.3.0&w=239",
  available: true,
  editable: true,
  from: "2022-05-24T00:00:00.000Z",
  to: "2022-05-31T00:00:00.000Z",
  updated: "2022-04-12T22:53:21.000Z",
  createdTime: "2022-04-12T22:53:21.000Z",
  advancedNoticeSec: 172800,
  whatToBringItems: [
    {
      id: 2846,
      name: "Driver's licence",
      included: true,
      __typename: "OrderWhatToBringItem",
    },
    {
      id: 6903,
      name: "Warm Clothes",
      included: true,
      __typename: "OrderWhatToBringItem",
    },
    {
      id: 6904,
      name: "Swimsuit",
      included: true,
      __typename: "OrderWhatToBringItem",
    },
    {
      id: 6905,
      name: "Camera",
      included: true,
      __typename: "OrderWhatToBringItem",
    },
  ],
  pickup: "FREE_PICKUP",
  pickupLocation: null,
  startingLocation: {
    locationName: "Keflavík Airport",
    __typename: "OrderTourCartLocation",
  },
  endingLocation: {
    locationName: "Keflavík Airport",
    __typename: "OrderTourCartLocation",
  },
  __typename: "OrderTourCartInfo",
};

export const cartCarMock = {
  id: "596",
  offerId: "596",
  cartItemId: "cars-4",
  category: "Small",
  pickupLocation: "Keflavík International Airport (KEF)",
  dropoffLocation: "Keflavík International Airport (KEF)",
  pickupId: "701,2",
  dropoffId: "701,2",
  dropoffSpecify: null,
  pickupSpecify: null,
  flightNumber: "",
  provider: "Monolith",
  numberOfDays: 7,
  priceOnArrival: 0,
  discountAmount: 856,
  discountPercentage: 2,
  extras: [],
  insurances: [],
  title: "Hyundai i10 2016 manual",
  totalPrice: 41949,
  priceBreakdown: [
    {
      id: "8d9a9849-2d38-43a0-be5e-eba9074ed943",
      name: "Car rental for 7 days in. Season: Jan - May Low",
      currency: "ISK",
      quantity: 7,
      pricePerUnit: 6115,
      pricePerUnitDisplay: "6,115",
      totalPrice: 42805,
      totalPriceDisplay: "42,805",
      isMinAmount: false,
      isMaxAmount: false,
      includeInBasePrice: true,
      type: "",
      translationKeys: {
        keys: [],
        __typename: "OrderTranslationKeys",
      },
      __typename: "OrderCartPriceBreakdown",
    },
    {
      id: "c0e46a86-56c0-4b0a-a830-e63f7cc4d524",
      name: "Discount on car rental",
      currency: "ISK",
      quantity: 1,
      pricePerUnit: 856,
      pricePerUnitDisplay: "856",
      totalPrice: 856,
      totalPriceDisplay: "856",
      isMinAmount: false,
      isMaxAmount: false,
      includeInBasePrice: false,
      type: "",
      translationKeys: {
        keys: [],
        __typename: "OrderTranslationKeys",
      },
      __typename: "OrderCartPriceBreakdown",
    },
  ],
  payOnArrival: [],
  imageUrl: "https://guidetoiceland.imgix.net/482259/x/0/1.jpg",
  available: true,
  editable: true,
  from: "2022-05-24T10:00:00.000Z",
  to: "2022-05-31T10:00:00.000Z",
  updated: "2022-04-12T23:09:57.000Z",
  createdTime: "2022-04-12T23:10:02.396Z",
  expiredTime: null,
  advancedNoticeSec: 172800,
  driverAge: 45,
  driverCountry: "IS",
  locationDetails: {
    pickup: {
      address: "Keflavík International Airport (KEF)",
      streetNumber: null,
      cityName: null,
      postalCode: null,
      state: null,
      country: null,
      phoneNumber: "",
      openingHours: [
        {
          isOpen: true,
          openFrom: "05:00:00",
          openTo: "18:00:00",
          dayOfWeek: 0,
          __typename: "OrderCarCartOpeningHours",
        },
        {
          isOpen: true,
          openFrom: "05:00:00",
          openTo: "18:00:00",
          dayOfWeek: 0,
          __typename: "OrderCarCartOpeningHours",
        },
        {
          isOpen: true,
          openFrom: "05:00:00",
          openTo: "18:00:00",
          dayOfWeek: 0,
          __typename: "OrderCarCartOpeningHours",
        },
        {
          isOpen: true,
          openFrom: "05:00:00",
          openTo: "18:00:00",
          dayOfWeek: 0,
          __typename: "OrderCarCartOpeningHours",
        },
        {
          isOpen: true,
          openFrom: "05:00:00",
          openTo: "18:00:00",
          dayOfWeek: 0,
          __typename: "OrderCarCartOpeningHours",
        },
        {
          isOpen: true,
          openFrom: "05:00:00",
          openTo: "18:00:00",
          dayOfWeek: 0,
          __typename: "OrderCarCartOpeningHours",
        },
        {
          isOpen: true,
          openFrom: "05:00:00",
          openTo: "18:00:00",
          dayOfWeek: 0,
          __typename: "OrderCarCartOpeningHours",
        },
      ],
      __typename: "OrderCarCartLocation",
    },
    dropoff: {
      address: "Keflavík International Airport (KEF)",
      streetNumber: null,
      cityName: null,
      postalCode: null,
      state: null,
      country: null,
      phoneNumber: "",
      openingHours: [
        {
          isOpen: true,
          openFrom: "05:00:00",
          openTo: "18:00:00",
          dayOfWeek: 0,
          __typename: "OrderCarCartOpeningHours",
        },
        {
          isOpen: true,
          openFrom: "05:00:00",
          openTo: "18:00:00",
          dayOfWeek: 0,
          __typename: "OrderCarCartOpeningHours",
        },
        {
          isOpen: true,
          openFrom: "05:00:00",
          openTo: "18:00:00",
          dayOfWeek: 0,
          __typename: "OrderCarCartOpeningHours",
        },
        {
          isOpen: true,
          openFrom: "05:00:00",
          openTo: "18:00:00",
          dayOfWeek: 0,
          __typename: "OrderCarCartOpeningHours",
        },
        {
          isOpen: true,
          openFrom: "05:00:00",
          openTo: "18:00:00",
          dayOfWeek: 0,
          __typename: "OrderCarCartOpeningHours",
        },
        {
          isOpen: true,
          openFrom: "05:00:00",
          openTo: "18:00:00",
          dayOfWeek: 0,
          __typename: "OrderCarCartOpeningHours",
        },
        {
          isOpen: true,
          openFrom: "05:00:00",
          openTo: "18:00:00",
          dayOfWeek: 0,
          __typename: "OrderCarCartOpeningHours",
        },
      ],
      __typename: "OrderCarCartLocation",
    },
    __typename: "OrderCarCartLoctionDetails",
  },
  vendor: {
    name: "City Car Rental",
    __typename: "OrderCarCartVendor",
  },
  __typename: "OrderCarCartInfo",
};

export const cartStayMock = {
  id: 619644534,
  address: "Laugarvegur 38, 101 Reykjavík",
  productId: 100,
  type: "apartment",
  uri: "/accommodation/cottages/centerspot-2-bedroom-apatment",
  numberOfGuests: 2,
  numberOfAdults: 0,
  numberOfChildren: 0,
  childrenAges: null,
  title: "Centerspot 2-Bedroom Apartment in Reykjavik",
  cartItemId: "hotels-5",
  discountAmount: 0,
  discountPercentage: 0,
  totalPrice: 251000,
  imageUrl:
    "https://guidetoiceland.imgix.net/546593/x/0/ecce79a9699ae59032b192ae5e379c15-jpg?crop=faces&fit=crop&h=239&ixlib=php-3.3.0&w=239",
  available: true,
  editable: true,
  currency: "ISK",
  from: "2022-05-24T15:00:00.000Z",
  to: "2022-05-31T11:00:00.000Z",
  updated: "2022-04-12T23:12:14.000Z",
  createdTime: "2022-04-12T23:12:14.000Z",
  cancellationPolicy: null,
  cancellationString: null,
  cityOsmId: null,
  cityName: null,
  countryOsmId: null,
  countryName: null,
  valueProps: [
    {
      iconId: "cancellation",
      title: "Free cancellation",
      __typename: "OrderValueProp",
    },
    {
      iconId: "customerSupport",
      title: "24/7 customer support",
      __typename: "OrderValueProp",
    },
    {
      iconId: "bestPrice",
      title: "Best price guarantee",
      __typename: "OrderValueProp",
    },
    {
      iconId: "instantConfirmation",
      title: "Instant confirmation",
      __typename: "OrderValueProp",
    },
    {
      iconId: "parking",
      title: "Parking available",
      __typename: "OrderValueProp",
    },
  ],
  rooms: [
    {
      id: 5295,
      type: "SR",
      name: "Cottages in Iceland",
      privateBathroom: true,
      size: 0,
      maxPersons: 6,
      roomBookings: [
        {
          extraBedCount: 0,
          adults: 2,
          children: 0,
          mesh: null,
          requestId: null,
          source: null,
          masterRateCode: null,
          extras: [
            {
              id: 1,
              name: "Final Cleaning",
              price: 10000,
              childPrice: 10000,
              required: 0,
              count: 1,
              chargeType: "per_order",
              __typename: "OrderStayCartExtra",
            },
            {
              id: 9,
              name: "Bedsheets and towels",
              price: 1000,
              childPrice: 1000,
              required: 0,
              count: 2,
              chargeType: "per_order",
              __typename: "OrderStayCartExtra",
            },
          ],
          __typename: "OrderStayCartRoom",
        },
      ],
      __typename: "OrderStayCartRoomInfo",
    },
  ],
  specs: [
    {
      iconId: "hotelCategory",
      name: "Category",
      value: "Cottage",
      __typename: "OrderProductSpec",
    },
    {
      iconId: "hotelRoom",
      name: "Room",
      value: "2 Bedrooms, 1 Living rooms",
      __typename: "OrderProductSpec",
    },
    {
      iconId: "hotelSleeps",
      name: "Sleeps",
      value: "6 Persons",
      __typename: "OrderProductSpec",
    },
    {
      iconId: "hotelLocation",
      name: "Location",
      value: "Laugarvegur 38, 101 Reykjavík",
      __typename: "OrderProductSpec",
    },
    {
      iconId: "hotelCheckInOut",
      name: "Check-in & out",
      value: "15:00 / 11:00",
      __typename: "OrderProductSpec",
    },
    {
      iconId: "hotelParking",
      name: "Parking",
      value: "Free parking",
      __typename: "OrderProductSpec",
    },
  ],
  __typename: "OrderStayCartInfo",
};

export const getCartRequestMock = ({
  cartData,
  preferredPaymentProvider,
}: {
  cartData: any;
  preferredPaymentProvider: string;
}) => {
  const mockCart = constructMockCartResponse({
    cartData,
    preferredPaymentProvider,
  });

  return RequestMock()
    .onRequestTo(
      request =>
        request.method === "post" && /cartWithPaymentProvidersQuery/.test(request.body.toString())
    )
    .respond(mockCart, 200);
};
